/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BitcoinAddress = string;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'btcPaymentAddress' : BitcoinAddress,
  'buyerContact' : string,
  'amountInBitcoin' : string,
}
export type OrderId = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'paid' : null } |
  { 'pendingPayment' : null } |
  { 'delivered' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [OrderId, string, BitcoinAddress, string],
    undefined
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];