/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'pendingPayment' : IDL.Null,
  'delivered' : IDL.Null,
});
export const BitcoinAddress = IDL.Text;
export const AdminStats = IDL.Record({
  'cancelledOrders' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'paidOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalContactMessages' : IDL.Nat,
  'totalUsdtRevenue' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'btcPaymentAddress' : BitcoinAddress,
  'denomination' : IDL.Nat,
  'buyerContact' : IDL.Text,
  'amountInBitcoin' : IDL.Text,
  'usdtAmount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'contactDetail' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateOrderStatus' : IDL.Func([IDL.Vec(OrderId), OrderStatus], [], []),
  'claimSiteOwner' : IDL.Func([], [], []),
  'createContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createOrder' : IDL.Func(
      [OrderId, IDL.Text, BitcoinAddress, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getOrdersByDenomination' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getSiteOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUnreadContactMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'pendingPayment' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const BitcoinAddress = IDL.Text;
  const AdminStats = IDL.Record({
    'cancelledOrders' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'paidOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalContactMessages' : IDL.Nat,
    'totalUsdtRevenue' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'btcPaymentAddress' : BitcoinAddress,
    'denomination' : IDL.Nat,
    'buyerContact' : IDL.Text,
    'amountInBitcoin' : IDL.Text,
    'usdtAmount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'contactDetail' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateOrderStatus' : IDL.Func([IDL.Vec(OrderId), OrderStatus], [], []),
    'claimSiteOwner' : IDL.Func([], [], []),
    'createContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createOrder' : IDL.Func(
        [OrderId, IDL.Text, BitcoinAddress, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getOrdersByDenomination' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getSiteOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getUnreadContactMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };