/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'cancelledOrders' : bigint,
  'totalOrders' : bigint,
  'paidOrders' : bigint,
  'pendingOrders' : bigint,
  'totalContactMessages' : bigint,
  'totalUsdtRevenue' : bigint,
  'deliveredOrders' : bigint,
}
export type BitcoinAddress = string;
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'isRead' : boolean,
  'contactDetail' : string,
  'message' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'btcPaymentAddress' : BitcoinAddress,
  'denomination' : bigint,
  'buyerContact' : string,
  'amountInBitcoin' : string,
  'usdtAmount' : bigint,
}
export type OrderId = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'paid' : null } |
  { 'pendingPayment' : null } |
  { 'delivered' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateOrderStatus' : ActorMethod<
    [Array<OrderId>, OrderStatus],
    undefined
  >,
  'claimSiteOwner' : ActorMethod<[], undefined>,
  'createContactMessage' : ActorMethod<[string, string, string], undefined>,
  'createOrder' : ActorMethod<
    [OrderId, string, BitcoinAddress, string, bigint, bigint],
    undefined
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrdersByDenomination' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getSiteOwner' : ActorMethod<[], [] | [Principal]>,
  'getUnreadContactMessageCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'markContactMessageAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];